repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run all checks (just check)
        entry: just check
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/gauge-sh/tach-pre-commit
    rev: v0.29.0 # ensure recent tag
    hooks:
      - id: tach